// Automatically generated by astro-icon
// 30273da7b77d2d2286546d78a2e38df3a79caf6e669d63f97ee5b36774896767

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "carbon:api-1"
		| "carbon:container-services"
		| "carbon:dashboard"
		| "carbon:app-connectivity"
		| "carbon:add"
		| "carbon:email"
		| "carbon:password"
		| "carbon:login"
		| "carbon:error"
		| "carbon:logout"
		| "iconoir:network-reverse"
		| "iconoir:view-structure-down"
		| "iconoir:cloud-sync"
		| "iconoir:electronics-chip"
		| "iconoir:database"
		| "iconoir:code"
		| "ri:arrow-down-double-fill"
		| "ri:arrow-down-circle-line"
		| "ri:close-circle-line"
		| "ri:mail-line"
		| "ri:key-fill"
		| "ri:menu-fill"
		| "ri:add-box-line"
		| "ri:file-copy-2-line"
		| "ri:settings-5-line"
		| "ri:user-add-line"
		| "ri:chat-new-line"
		| "ri:code-box-line"
		| "ri:menu-2-fill"
		| "ri:file-list-3-line"
		| "ri:home-2-line"
		| "ri:user-3-line";
}